In [1]:
import numpy as np

In [3]:
nx, ny = (3, 2)

In [5]:
x = np.linspace(0, 1, nx)
x

array([0. , 0.5, 1. ])

In [6]:
y = np.linspace(0, 1, ny)
y

array([0., 1.])

In [7]:
xv, yv = np.meshgrid(x, y)

In [8]:
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [9]:
yv

array([[0., 0., 0.],
       [1., 1., 1.]])

In [10]:
radius = 20
window = 2 * radius + 1
x, y = np.meshgrid(np.arange(-radius, radius + 1), np.arange(-radius, radius + 1))

In [13]:
offset_cost = np.stack([x, y], axis=-1)
offset_cost.shape

(41, 41, 2)

In [30]:
print(offset_cost[1, 2])

[-18 -19]
