In [1]:
import numpy as np

In [3]:
nx, ny = (3, 2)

In [5]:
x = np.linspace(0, 1, nx)
x

array([0. , 0.5, 1. ])

In [6]:
y = np.linspace(0, 1, ny)
y

array([0., 1.])

In [7]:
xv, yv = np.meshgrid(x, y)

In [8]:
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [9]:
yv

array([[0., 0., 0.],
       [1., 1., 1.]])

In [10]:
radius = 20
window = 2 * radius + 1
x, y = np.meshgrid(np.arange(-radius, radius + 1), np.arange(-radius, radius + 1))

In [13]:
offset_cost = np.stack([x, y], axis=-1)
offset_cost.shape

(41, 41, 2)

In [30]:
print(offset_cost[1, 2])

[-18 -19]


In [23]:
import torch

data = torch.randint(1, 10, (6, 10))
data

tensor([[3, 5, 5, 5, 4, 5, 4, 9, 1, 1],
        [2, 6, 3, 1, 6, 5, 8, 8, 8, 4],
        [5, 7, 8, 5, 6, 1, 5, 8, 5, 5],
        [7, 5, 1, 9, 4, 8, 1, 4, 9, 3],
        [2, 4, 7, 8, 7, 6, 8, 1, 8, 3],
        [6, 1, 8, 5, 3, 2, 3, 1, 4, 8]])

In [25]:
unfolded = data.unfold(0, 2, 1)
print(unfolded.shape)
print(unfolded)

torch.Size([5, 10, 2])
tensor([[[3, 2],
         [5, 6],
         [5, 3],
         [5, 1],
         [4, 6],
         [5, 5],
         [4, 8],
         [9, 8],
         [1, 8],
         [1, 4]],

        [[2, 5],
         [6, 7],
         [3, 8],
         [1, 5],
         [6, 6],
         [5, 1],
         [8, 5],
         [8, 8],
         [8, 5],
         [4, 5]],

        [[5, 7],
         [7, 5],
         [8, 1],
         [5, 9],
         [6, 4],
         [1, 8],
         [5, 1],
         [8, 4],
         [5, 9],
         [5, 3]],

        [[7, 2],
         [5, 4],
         [1, 7],
         [9, 8],
         [4, 7],
         [8, 6],
         [1, 8],
         [4, 1],
         [9, 8],
         [3, 3]],

        [[2, 6],
         [4, 1],
         [7, 8],
         [8, 5],
         [7, 3],
         [6, 2],
         [8, 3],
         [1, 1],
         [8, 4],
         [3, 8]]])
